# Generated by Django 3.2.8 on 2021-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_code', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('query_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
