# Generated by Django 3.2.8 on 2021-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataquery',
            name='scale',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
