# Generated by Django 3.2.8 on 2021-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataquery_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataquery',
            name='query',
            field=models.JSONField(null=True),
        ),
    ]
